package com.assetflow.notification;

public enum NotificationType {
    ASSET_ASSIGNED,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    BOOKING_REMINDER,
    MAINTENANCE_APPROVED,
    MAINTENANCE_REJECTED,
    OVERDUE_RETURN,
    AUDIT_ASSIGNED,
    AUDIT_DISCREPANCY
}
