package com.assetflow.maintenance.entity;

import com.assetflow.common.BaseEntity;
import com.assetflow.common.MaintenanceStatus;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Represents a maintenance request raised for an asset.
 *
 * Request numbers follow the format MR-0001, MR-0002, …
 * They are generated safely in the service layer (not via count()+1).
 *
 * Uses optimistic locking via {@code @Version}.
 * No JPA relationships to other members' entities — only IDs stored.
 */
@Entity
@Table(name = "maintenance_requests",
        indexes = {
            @Index(name = "idx_mr_asset_id", columnList = "assetId"),
            @Index(name = "idx_mr_raised_by", columnList = "raisedByUserId"),
            @Index(name = "idx_mr_status", columnList = "status"),
            @Index(name = "idx_mr_request_number", columnList = "requestNumber", unique = true)
        })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class MaintenanceRequest extends BaseEntity {

    /** Format: MR-0001, MR-0002, … Generated by service. */
    @Column(nullable = false, unique = true, length = 20)
    private String requestNumber;

    /** FK to the asset — ID only, no JPA relation. */
    @Column(nullable = false)
    private Long assetId;

    /** FK to the user who raised the request. */
    @Column(nullable = false)
    private Long raisedByUserId;

    @Column(nullable = false, length = 2000)
    private String issueDescription;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private MaintenancePriority priority;

    @Column(length = 500)
    private String attachmentUrl;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private MaintenanceStatus status = MaintenanceStatus.PENDING;

    /** FK to the user who approved the request. */
    @Column
    private Long approvedByUserId;

    private LocalDateTime approvedAt;

    @Column(length = 1000)
    private String rejectionReason;

    /** FK to the assigned technician's user account. */
    @Column
    private Long technicianUserId;

    private LocalDateTime technicianAssignedAt;

    private LocalDateTime repairStartedAt;

    private LocalDateTime resolvedAt;

    @Column(length = 2000)
    private String resolutionNotes;

    /** Optimistic locking version field. */
    @Version
    private Long version;
}
